services:
  server:
    build:
      context: ./app
    env_file:
      - ./app/config/.env
    ports:
      - 80:80
    develop:
      watch:
        - action: sync
          path: ./app/
          target: /var/www/html/

  db:
    image: mysql:8.4.8
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./app/config/database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
